### ISSUE TITLE
insert into rect2 values (1, rectangle(1 2 3 4), 233);

### ISSUE THREAD

**Issue by YANNINGLI97** [datajaguar/jaguardb#27]
the value b of rectangle can't be inserted to database;
sql:
insert into rect2 values (1, rectangle(1 2 3 4), 233);
result as following:
a=[1] r1:x=[1.0] r1:y=[2.0] r1:a=[3.0] r1:b=[0.0] r1:nx=[0.0] c=[] 

sql:
insert into rect2 values (1, rectangle(1 2 3 4 5), 233);
result as following:
a=[1] r1:x=[1.0] r1:y=[2.0] r1:a=[3.0] r1:b=[5.0] r1:nx=[0.0] c=[]

**Comment by datajaguar** [comment]
complete
